### ISSUE TITLE
Cannot add this package to my project

### ISSUE THREAD

**Issue by ntoka** [dfischer/meteor-prerenderio#22]
Hi, 

i'm trying to add this package to my meteor app, but keep getting this error: 

`Error: ENOENT, open 'C:\Users\KSEND_~1\AppData\Local\Temp\mt-1td10o1\os\dfi
scher:prerenderio.js'
    at Object.Future.wait (C:\Users\ksend_000\AppData\Local\.meteor\package
s\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fiber
s\future.js:398:15)
`

Adding other packages works fine. Meteor version is 1.2.1.

What can be wrong?

**Comment by matthieuh** [comment]
I have the same issue, a windows problem. I'm trying to resolve it.

**Comment by cricku** [comment]
same problem here, no fix until now :(

**Comment by dfischer** [comment]
Not able to test on Windows, my apologies.

**Comment by rynti** [comment]
It appears the issue is that the files have colons in their names (for instance `dfisher:prerenderio.js`), which is not supported on Windows. However, this can very easily be fixed by simply replacing the colon with an underscore or other compatible character.

A fix would be really appreciated @dfischer :)

**Comment by dfischer** [comment]
Feel free to open PR @rynti sounds easy enough (currently traveling, but happy to test quickly with a PR)

**Comment by rynti** [comment]
#25 looks great! @dfischer have you had a chance to look at it?

**Comment by dfischer** [comment]
@rynti merging now

**Comment by cricku** [comment]
@dfischer thanks, now it's working great on Windows.
